### AVISO: Ao digitar a altura use o ponto(.) ao invés de vírgula (,)

In [3]:
jogadoras = []

for convocadas in range (14):
    nome = input("\nNome da jogadora: ").title().strip()
    numero = int(input('Nº da jogadora: '))
    idade = int(input('Idade : '))
    altura = float(input ('Altura: '))
    posicao = input ('Posição: ').title().strip()
    convocacao = [nome, numero, idade, altura, posicao]
    jogadoras.append(convocacao)

Nome da jogadora: Júlia Kudiess
Nº da jogadora: 3
Idade : 19
Altura: 1.92
Posição: meio de rede

Nome da jogadora: carol
Nº da jogadora: 4
Idade : 31
Altura: 1.83
Posição: Meio de rede

Nome da jogadora: Pri Daroit
Nº da jogadora: 5
Idade : 33
Altura: 1.84
Posição: ponteira

Nome da jogadora: Nyeme
Nº da jogadora: 6
Idade : 23
Altura: 1.75
Posição: líbero

Nome da jogadora: Rosamaria
Nº da jogadora: 7
Idade : 28
Altura: 1.84
Posição: ponteira

Nome da jogadora: Macris
Nº da jogadora: 8
Idade : 33
Altura: 1.78
Posição: levantadora

Nome da jogadora: roberta
Nº da jogadora: 9
Idade : 32
Altura: 1.85
Posição: Levantadora

Nome da jogadora: gabi
Nº da jogadora: 10
Idade : 28
Altura: 1.80
Posição: ponteira

Nome da jogadora: Ana cristina
Nº da jogadora: 12
Idade : 18
Altura: 1.92
Posição: ponteira

Nome da jogadora: Natinha
Nº da jogadora: 14
Idade : 25
Altura: 1.62
Posição: líbero

Nome da jogadora: Lorena
Nº da jogadora: 15
Idade : 22
Altura: 1.90
Posição: meio de rede

Nome da jogadora: Kisy
Nº da jogadora: 16
Idade : 22
Altura: 1.91
Posição: Oposto

Nome da jogadora: Júlia B.
Nº da jogadora: 17
Idade : 21
Altura: 1.96
Posição: Ponteira

Nome da jogadora: Lorene
Nº da jogadora: 24
Idade : 26
Altura: 1.87
Posição: oposto

In [4]:
media_idade = 0
media_altura = 0

for nome, numero, idade, altura, posicao in jogadoras:
    media_idade += idade/14
    media_altura += altura/14
    
print('\n')
print ('='*21, "CONVOCADAS", '='*21)
print ('| Nº |      NOME     | IDADE | ALTURA |   POSIÇÃO    |')
print ("-"*54)
for i in jogadoras:
    indice = jogadoras.index(i)
    texto = "|{:^4}|{:<15}|{:^7}|{:^8,.2f}|{:>14}|"
    print (texto.format(jogadoras[indice][1], jogadoras[indice][0], jogadoras[indice][2], jogadoras[indice][3],jogadoras[indice][4]))
print ("-"*54)
print('|   MÉDIA DE IDADE         |       MEDIA DE ALTURA   |')
print('|   {:<8,.2f}               |              {:>8,.2f}   |' .format(media_idade,media_altura))
print ("-"*54)

===================== CONVOCADAS =====================
| Nº |      NOME     | IDADE | ALTURA |   POSIÇÃO    |
------------------------------------------------------
| 3  |Júlia Kudiess  |  19   |  1.92  |  Meio De Rede|
| 4  |Carol          |  31   |  1.83  |  Meio De Rede|
| 5  |Pri Daroit     |  33   |  1.84  |      Ponteira|
| 6  |Nyeme          |  23   |  1.75  |        Líbero|
| 7  |Rosamaria      |  28   |  1.84  |      Ponteira|
| 8  |Macris         |  33   |  1.78  |   Levantadora|
| 9  |Roberta        |  32   |  1.85  |   Levantadora|
| 10 |Gabi           |  28   |  1.80  |      Ponteira|
| 12 |Ana Cristina   |  18   |  1.92  |      Ponteira|
| 14 |Natinha        |  25   |  1.62  |        Líbero|
| 15 |Lorena         |  22   |  1.90  |  Meio De Rede|
| 16 |Kisy           |  22   |  1.91  |        Oposto|
| 17 |Júlia B.       |  21   |  1.96  |      Ponteira|
| 24 |Lorene         |  26   |  1.87  |        Oposto|
------------------------------------------------------
|   MÉDIA DE IDADE         |       MEDIA DE ALTURA   |
|   25.79                  |                  1.84   |
------------------------------------------------------